# Generated by Django 5.1.7 on 2025-03-09 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('photo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FellowProfile',
            fields=[
                ('type_of_college', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_of_study', models.CharField(blank=True, max_length=100, null=True)),
                ('technical_skills', models.TextField(blank=True, null=True)),
                ('artistic_skills', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
