# Generated by Django 5.1.7 on 2025-03-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserRegistration',
        ),
    ]
