# Generated by Django 5.1.7 on 2025-03-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_userregistration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistration',
            new_name='UserSignUp',
        ),
    ]
