# Generated by Django 5.1.7 on 2025-03-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_userregistration_usersignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='full_name',
            field=models.CharField(default='', editable=False, max_length=101),
            preserve_default=False,
        ),
    ]
