# Generated by Django 5.1.7 on 2025-03-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usersignup_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='final_access_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='has_agreed_to_child_protection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='has_agreed_to_data_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='has_submitted_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
