# Generated by Django 4.2.24 on 2025-10-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pendinguser_otpverification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otpverification',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(max_length=4),
        ),
    ]
