# Generated by Django 4.2.24 on 2025-10-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_otpverification_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='speaker',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma-separated languages', max_length=200),
        ),
        migrations.AddField(
            model_name='speaker',
            name='location',
            field=models.CharField(blank=True, help_text='City, State/Country', max_length=200),
        ),
    ]
