# Generated by Django 5.1.7 on 2025-03-15 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_castecategory_district_state_mandal_grampanchayat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('caste_category', models.CharField(max_length=20)),
                ('insert_timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.district')),
                ('mandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mandal')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.state')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grampanchayat')),
            ],
            options={
                'db_table': 'registrations',
                'ordering': ['-insert_timestamp'],
            },
        ),
    ]
