# Generated by Django 5.1.7 on 2025-03-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_registration_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='api_registration',
        ),
    ]
