# Generated by Django 5.1.7 on 2025-03-17 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_registration_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='istask1submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='istask2submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='isvideo1seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='isvideo2seen',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task1_status', models.CharField(choices=[('Yet to Complete', 'Yet to Complete'), ('Sent for Review', 'Sent for Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Yet to Complete', max_length=50)),
                ('lc_photo', models.ImageField(blank=True, null=True, upload_to='lc_photos/')),
                ('task2_status', models.CharField(choices=[('Yet to Complete', 'Yet to Complete'), ('Sent for Review', 'Sent for Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Yet to Complete', max_length=50)),
                ('training_photo', models.ImageField(blank=True, null=True, upload_to='training_photos/')),
                ('video1_watched', models.BooleanField(default=False)),
                ('video2_watched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.district')),
                ('selected_mandal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mandal')),
                ('selected_village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.grampanchayat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usersignup')),
            ],
            options={
                'db_table': 'task_status',
            },
        ),
    ]
