# Generated by Django 5.1.7 on 2025-03-17 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_registration_istask1submitted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('lc_photo_s3_url', models.URLField(blank=True, max_length=500, null=True)),
                ('students_marks_s3_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lc_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.district')),
                ('lc_grampanchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grampanchayat')),
                ('lc_mandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mandal')),
                ('lc_state', models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, to='api.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_centers', to='api.usersignup')),
            ],
            options={
                'db_table': 'learning_center',
            },
        ),
    ]
