# Generated by Django 4.2.26 on 2025-11-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_pendinguser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speaker",
            options={"ordering": ["-created_at"]},
        ),
    ]
