# Generated by Django 5.1.7 on 2025-03-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_task_details'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task_details',
            table='task_details',
        ),
    ]
