# Generated by Django 5.1.7 on 2025-03-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='task1_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('UNDER_REVIEW', 'Under Review'), ('SENT_BACK', 'Sent Back'), ('APPROVED', 'Approved'), ('NOT_APPROVED', 'Not Approved')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='task2_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('UNDER_REVIEW', 'Under Review'), ('SENT_BACK', 'Sent Back'), ('APPROVED', 'Approved'), ('NOT_APPROVED', 'Not Approved')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterModelTable(
            name='task_details',
            table=None,
        ),
    ]
