# Generated by Django 5.1.7 on 2025-03-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_registration_task1_status_registration_task2_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='profile_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
