# Generated by Django 5.1.7 on 2025-03-20 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_usersignup_profile_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fellow_id', models.CharField(blank=True, max_length=50)),
                ('team_leader', models.CharField(blank=True, max_length=100)),
                ('fellow_status', models.CharField(default='Active', max_length=20)),
                ('performance_score', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('caste_category', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('mandal', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('current_job', models.CharField(blank=True, max_length=100)),
                ('hobbies', models.TextField(blank=True)),
                ('college_name', models.CharField(blank=True, max_length=200)),
                ('type_of_college', models.CharField(blank=True, max_length=50)),
                ('study_mode', models.CharField(blank=True, max_length=50)),
                ('stream', models.CharField(blank=True, max_length=100)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('subjects', models.TextField(blank=True)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('technical_skills', models.TextField(blank=True)),
                ('artistic_skills', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_profile', to='api.usersignup')),
            ],
        ),
    ]
