# Generated by Django 5.1.7 on 2025-03-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_fellowprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='accepted_offer_letter_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='is_accepted_offer_letter',
            field=models.BooleanField(default=False),
        ),
    ]
