# Generated by Django 5.1.7 on 2025-03-28 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_usersignup_accepted_offer_letter_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FellowRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('caste_category', models.CharField(choices=[('ST', 'ST'), ('SC', 'SC'), ('BC', 'BC'), ('OBC', 'OBC'), ('OC', 'OC'), ('MUSLIM', 'Muslim'), ('CHRISTIAN', 'Christian'), ('OTHER', 'Other')], max_length=20)),
                ('task1_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('UNDER_REVIEW', 'Under Review'), ('SENT_BACK', 'Sent Back'), ('APPROVED', 'Approved'), ('NOT_APPROVED', 'Not Approved')], default='NOT_STARTED', max_length=20)),
                ('task2_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('UNDER_REVIEW', 'Under Review'), ('SENT_BACK', 'Sent Back'), ('APPROVED', 'Approved'), ('NOT_APPROVED', 'Not Approved')], default='NOT_STARTED', max_length=20)),
                ('isvideo1seen', models.BooleanField(default=False)),
                ('isvideo2seen', models.BooleanField(default=False)),
                ('istask1submitted', models.BooleanField(default=False)),
                ('istask2submitted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('batch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FellowSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=50)),
                ('given_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(editable=False, max_length=101)),
                ('password', models.CharField(max_length=100)),
                ('unique_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('has_submitted_tasks', models.BooleanField(default=False)),
                ('has_agreed_to_data_consent', models.BooleanField(default=False)),
                ('has_agreed_to_child_protection', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_accepted_offer_letter', models.BooleanField(default=False)),
                ('accepted_offer_letter_date', models.DateTimeField(blank=True, null=True)),
                ('final_access_granted', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('mobile_number', 'full_name')},
            },
        ),
        migrations.CreateModel(
            name='FellowTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorder_type', models.CharField(max_length=50)),
                ('audio_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fellow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fellowsignup')),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='district',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='mandal',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='state',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='village',
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
        migrations.RenameField(
            model_name='castecategory',
            old_name='name',
            new_name='caste_category_name',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='district_name',
        ),
        migrations.RenameField(
            model_name='grampanchayat',
            old_name='name',
            new_name='gram_panchayat_name',
        ),
        migrations.RenameField(
            model_name='mandal',
            old_name='name',
            new_name='mandal_name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='state_name',
        ),
        migrations.RemoveField(
            model_name='fellowprofile',
            name='caste_category',
        ),
        migrations.RemoveField(
            model_name='fellowprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='fellowprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='fellowprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='fellowprofile',
            name='mandal',
        ),
        migrations.RemoveField(
            model_name='fellowprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='fellowprofile',
            name='village',
        ),
        migrations.RemoveField(
            model_name='fellowprofile',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='fellowprofile',
            name='any_job_at_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fellowprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='fellowprofile',
            name='profile_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fellowprofile',
            name='fellow_status',
            field=models.CharField(default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='fellowregistration',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.district'),
        ),
        migrations.AddField(
            model_name='fellowregistration',
            name='grampanchayat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grampanchayat'),
        ),
        migrations.AddField(
            model_name='fellowregistration',
            name='mandal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mandal'),
        ),
        migrations.AddField(
            model_name='fellowregistration',
            name='state',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, to='api.state'),
        ),
        migrations.RenameModel(
            old_name='Task_details',
            new_name='TaskDetails',
        ),
        migrations.AddField(
            model_name='fellowregistration',
            name='fellow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_registration', to='api.fellowsignup'),
        ),
        migrations.AddField(
            model_name='fellowphoto',
            name='fellow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fellowsignup'),
        ),
        migrations.AlterField(
            model_name='fellowprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_profile', to='api.fellowsignup'),
        ),
        migrations.AlterField(
            model_name='taskdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_centers', to='api.fellowsignup'),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='UserSignUp',
        ),
    ]
