# Generated by Django 5.1.7 on 2025-03-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_fellowphoto_fellowregistration_fellowsignup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellowregistration',
            name='mobile_number',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
