# Generated by Django 5.1.7 on 2025-03-29 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_college_university_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fellowprofile',
            name='college_name',
        ),
        migrations.AddField(
            model_name='fellowprofile',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fellowprofile',
            name='batch',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fellowprofile',
            name='caste_category',
            field=models.CharField(blank=True, choices=[('ST', 'ST'), ('SC', 'SC'), ('BC', 'BC'), ('OBC', 'OBC'), ('OC', 'OC'), ('MUSLIM', 'Muslim'), ('CHRISTIAN', 'Christian'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fellowprofile',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.college'),
        ),
        migrations.AddField(
            model_name='fellowprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fellowprofile',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.district'),
        ),
        migrations.AddField(
            model_name='fellowprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.AddField(
            model_name='fellowprofile',
            name='grampanchayat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.grampanchayat'),
        ),
        migrations.AddField(
            model_name='fellowprofile',
            name='mandal',
            field=models.ForeignKey(default=304, on_delete=django.db.models.deletion.CASCADE, to='api.mandal'),
        ),
        migrations.AddField(
            model_name='fellowprofile',
            name='state',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, to='api.state'),
        ),
        migrations.AddField(
            model_name='fellowprofile',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.university'),
        ),
        migrations.AlterField(
            model_name='fellowprofile',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course'),
        ),
        migrations.AlterField(
            model_name='fellowprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='fellowprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_profile', to='api.fellowsignup'),
        ),
    ]
