# Generated by Django 5.1.7 on 2025-03-29 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_college_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.college'),
        ),
        migrations.RenameField(
            model_name='fellowprofile',
            old_name='type_of_college',
            new_name='type_of_college',
        ),
        migrations.AlterField(
            model_name='fellowprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course'),
        ),
        migrations.AlterField(
            model_name='fellowprofile',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fellowprofile',
            name='stream',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fellowprofile',
            name='study_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fellowprofile',
            name='subjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fellowprofile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.university'),
        ),
    ]
