# Generated by Django 5.1.7 on 2025-04-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_fellowprofile_type_of_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('fellow', models.JSONField(default=list)),
                ('fellow_parent', models.JSONField(default=list)),
                ('child', models.JSONField(default=list)),
                ('childs_parent', models.JSONField(default=list)),
                ('supporter', models.JSONField(default=list)),
                ('testimonial_urls', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('stakeholder_type', models.CharField(choices=[('fellow', 'Fellow'), ('fellow_parent', 'Fellow Parent'), ('child', 'Child'), ('childs_parent', "Child's Parent"), ('supporter', 'Supporter')], max_length=20)),
                ('audio_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
