# Generated by Django 5.1.7 on 2025-04-11 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_testimonialprogress_testimonialrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('team_lead_name', models.CharField(max_length=255)),
                ('district_lead_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=10)),
                ('full_address', models.TextField()),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.district')),
                ('mandal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mandal')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.state')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.grampanchayat')),
            ],
        ),
    ]
