# Generated by Django 5.1.7 on 2025-04-12 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_testimonialprogress_testimonialrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildrenProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("parent_mobile_number", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "caste_category",
                    models.CharField(
                        choices=[
                            ("ST", "ST"),
                            ("SC", "SC"),
                            ("BC", "BC"),
                            ("OBC", "OBC"),
                            ("OC", "OC"),
                            ("MUSLIM", "Muslim"),
                            ("CHRISTIAN", "Christian"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("school_name", models.CharField(blank=True, max_length=200)),
                ("type_of_school", models.CharField(blank=True, max_length=50)),
                ("child_class", models.CharField(blank=True, max_length=10)),
                ("admission_status", models.CharField(blank=True, max_length=20)),
                ("mother_name", models.CharField(blank=True, max_length=100)),
                ("mother_occupation", models.CharField(blank=True, max_length=100)),
                ("father_name", models.CharField(blank=True, max_length=100)),
                ("father_occupation", models.CharField(blank=True, max_length=100)),
                ("speaking_level", models.CharField(blank=True, max_length=20)),
                ("reading_level", models.CharField(blank=True, max_length=20)),
                (
                    "child_photo_s3_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.district",
                    ),
                ),
                (
                    "fellow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="api.fellowsignup",
                    ),
                ),
                (
                    "mandal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.mandal",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.state",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.grampanchayat",
                    ),
                ),
            ],
        ),
    ]
