# Generated by Django 5.1.7 on 2025-04-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_childrenprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="childrenprofile",
            old_name="admission_status",
            new_name="status",
        ),
    ]
