# Generated by Django 5.1.7 on 2025-04-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_learningcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcenter',
            name='lc_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
