# Generated by Django 5.1.7 on 2025-04-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_learningcenter_lc_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcenter',
            name='lc_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
