# Generated by Django 5.1.7 on 2025-04-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_rename_admission_status_childrenprofile_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="childrenprofile",
            old_name="village",
            new_name="grampanchayat",
        ),
    ]
