# Generated by Django 5.1.7 on 2025-04-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_rename_village_childrenprofile_grampanchayat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childrenprofile",
            name="child_class",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="childrenprofile",
            name="reading_level",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="childrenprofile",
            name="speaking_level",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="childrenprofile",
            name="status",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
