# Generated by Django 5.1.7 on 2025-04-15 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_learningcenter_lc_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictLead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.district'),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='mandal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mandal'),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.state'),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.grampanchayat'),
        ),
        migrations.AddField(
            model_name='district',
            name='district_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.districtlead'),
        ),
        migrations.CreateModel(
            name='TeamLead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('district_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leads', to='api.districtlead')),
            ],
        ),
    ]
