# Generated by Django 5.1.7 on 2025-04-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_districtlead_alter_learningcenter_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_lead',
        ),
        migrations.AddField(
            model_name='districtlead',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_leads', to='api.district'),
        ),
        migrations.AddField(
            model_name='districtlead',
            name='dl_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='districtlead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
