# Generated by Django 5.1.7 on 2025-04-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_district_district_lead_districtlead_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcenter',
            name='colony_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='door_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
