# Generated by Django 5.1.7 on 2025-04-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_learningcenter_colony_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcenter',
            name='full_address',
        ),
    ]
