# Generated by Django 5.1.7 on 2025-04-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_childrenprofile_child_class_and_more'),
        ('api', '0032_remove_learningcenter_full_address'),
    ]

    operations = [
    ]
