# Generated by Django 5.1.7 on 2025-04-20 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_merge_20250419_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('week', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fellow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fellowprofile')),
            ],
            options={
                'unique_together': {('fellow', 'date')},
            },
        ),
    ]
