# Generated by Django 5.1.7 on 2025-05-01 09:13


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

        ("api", "0034_childrenattendance"),
        ("api", "0034_fellowattendance"),
    ]

    operations = []

        

