# Generated by Django 5.1.7 on 2025-04-26 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_merge_0034_childrenattendance_0034_fellowattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fellow_mobile_number', models.CharField(max_length=15)),
                ('assessment_type', models.CharField(choices=[('baseline', 'Baseline'), ('endline', 'Endline')], max_length=10)),
                ('reading_level', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Proficient', 'Proficient')], max_length=20)),
                ('speaking_level', models.CharField(choices=[('Emergent', 'Emergent'), ('Letter', 'Letter'), ('Word', 'Word'), ('Para', 'Para'), ('Story', 'Story')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='api.childrenprofile')),
            ],
        ),
    ]
