# Generated by Django 5.1.7 on 2025-05-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_merge_0034_childrenattendance_0034_fellowattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="fellowprofile",
            name="college_other",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fellowprofile",
            name="course_other",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fellowprofile",
            name="university_other",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
