# Generated by Django 5.1.7 on 2025-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_studentassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
