# Generated by Django 5.1.7 on 2025-05-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_fellowtaskstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowTaskStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveIntegerField()),
                ('task_name', models.CharField(max_length=255)),
                ('assigned_date', models.DateField()),
                ('deadline_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='FellowTaskStatus',
        ),
    ]
