# Generated by Django 5.1.7 on 2025-05-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_fellowtaskstatusupdate_delete_fellowtaskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowtaskstatusupdate',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
    ]
