# Generated by Django 5.1.7 on 2025-05-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_fellowprofile_college_other_and_more'),
        ('api', '0040_alter_fellowtaskstatusupdate_status'),
    ]

    operations = [
    ]
