# Generated by Django 5.1.7 on 2025-05-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_merge_20250501_1831"),
    ]

    operations = [
        migrations.AddField(
            model_name="fellowprofile",
            name="religion",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
