# Generated by Django 5.1.7 on 2025-05-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_fellowprofile_religion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fellowprofile",
            name="caste_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ST", "ST"),
                    ("SC", "SC"),
                    ("BC", "BC"),
                    ("OBC", "OBC"),
                    ("OC", "OC"),
                    ("Muslim", "Muslim"),
                    ("Christian", "Christian"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fellowprofile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="OTHER",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="fellowregistration",
            name="caste_category",
            field=models.CharField(
                choices=[
                    ("ST", "ST"),
                    ("SC", "SC"),
                    ("BC", "BC"),
                    ("OBC", "OBC"),
                    ("OC", "OC"),
                    ("Muslim", "Muslim"),
                    ("Christian", "Christian"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fellowregistration",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
            ),
        ),
    ]
