# Generated by Django 5.1.7 on 2025-05-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_merge_20250503_1751"),
        ("api", "0043_alter_fellowprofile_caste_category_and_more"),
    ]

    operations = []
