from django.urls import path
from .views import (
    HelloworldView,
    fellow_signup,
    fellow_login,
    fellow_register,
    forgot_password,
    update_tasks,
    update_data_consent,
    update_child_protection_consent,
    get_user_status,
    get_states,
    get_fellow_details,
    get_districts,
    get_mandals,
    get_grampanchayats,
    get_user_details,
    get_task_status,
    get_video_status,
    update_video_status,
    submit_task1,
    submit_task2,
    upload_profile_photo,
    get_fellow_profile,
    update_fellow_profile,
    update_fellow_acceptance,
    get_fellow_acceptance,
    save_fellow_testimonial,
    get_fellow_details_for_consent,
    get_universities,
    get_colleges,
    get_courses,
    SubmitTestimonialView,
    RecorderSummaryView,
    save_child_profile,
    get_child_profiles,
    get_child_profile_by_id,
    upload_child_photo,
    delete_child_profile,

    save_learning_center,
    get_learning_center,
    upload_lc_photo,
    delete_lc_photo,
    get_district_leads_by_district,
    get_team_leads_by_dl,
    save_fellow_attendance,
    get_fellow_attendance_history,
)   

urlpatterns = [
    path('fellow/profile/<str:mobile_number>/accept/', update_fellow_acceptance, name='update_fellow_acceptance'),
    path('fellow/profile/<str:mobile_number>/acceptance-status/', get_fellow_acceptance, name='get_fellow_acceptance'),
    path('fellow/profile/details/<str:mobile_number>/', get_fellow_profile, name='get_fellow_profile'),
    path('fellow/profile/<str:mobile_number>/<str:section>/', update_fellow_profile, name='update_fellow_profile'),
    
    path('', HelloworldView.as_view(), name='hello-world'),
    path('fellow/signup/', fellow_signup, name='fellow_signup'),
    path('fellow/login/', fellow_login, name='fellow_login'),
    path('fellow/register/', fellow_register, name='fellow_register'),
    path('forgot-password/', forgot_password, name='forgot_password'),
    path('fellow-details/', get_fellow_details, name='get_fellow_details'),
    path('fellow/data-consent/update/', update_data_consent, name='update_data_consent'),
    path('fellow/child-protection/update/', update_child_protection_consent, name='update_child_protection'),
    path('fellow/status/<str:mobile_number>/', get_user_status, name='get_user_status'),

    # location api   
    path('states/', get_states, name='get_states'),
    path('districts/', get_districts, name='get_districts'),
    path('mandals/', get_mandals, name='get_mandals'),
    path('grampanchayats/', get_grampanchayats, name='get_grampanchayats'),

    # task api
    path('user-details/', get_user_details, name='get_user_details'),
    path('fellow/tasks/status/<str:mobile_number>/', get_task_status, name='get_task_status'),
    path('tasks/video-status/update/', update_video_status, name='update_video_status'),
    path('tasks/video-status/<str:mobile_number>/', get_video_status, name='get_video_status'),

    path('fellow/tasks/submit/task1/', submit_task1, name='submit_task1'),
    path('fellow/tasks/submit/task2/', submit_task2, name='submit_task2'),

    path('fellow/profile/photo/upload/', upload_profile_photo, name='upload_profile_photo'),
    path('fellow/testimonial/upload/', save_fellow_testimonial, name='save_fellow_testimonial'),
    path('fellow/details/<str:mobile_number>/', get_fellow_details_for_consent, name='get_fellow_details_for_consent'),
    path('universities/', get_universities, name='get_universities'),
    path('colleges/', get_colleges, name='get_colleges'),
    path('courses/', get_courses, name='get_courses'),  
    path("submit-testimonial/", SubmitTestimonialView.as_view(), name="submit-testimonial"),
    path("recorder-summary/", RecorderSummaryView.as_view(), name="recorder-summary"),
    path("children/profile/save/", save_child_profile, name="save_child_profile"),
    path("children/profile/<int:child_id>/", get_child_profile_by_id, name="get_child_profile_by_id"),
    path("children/profile/list/<str:mobile_number>/", get_child_profiles, name="get_child_profiles"),
    path("children/photo/upload/", upload_child_photo, name="upload_child_photo"),
    path("children/profile/delete/<int:child_id>/", delete_child_profile, name="delete_child_profile"),
    #Learning Center API
    path('learning-center/save/', save_learning_center, name='save_learning_center'),
    path('learning-center/<str:mobile_number>/', get_learning_center, name='get_learning_center'),
    path('learning-center/photo/upload/', upload_lc_photo, name='upload_lc_photo'),
    path('learning-center/photo/delete/', delete_lc_photo, name='delete_lc_photo'),
    path('district-leads/<str:district_id>/', get_district_leads_by_district, name='get_district_leads_by_district'),
    path('team-leads/', get_team_leads_by_dl, name='get_team_leads_by_dl'),
    #attendance api
    path('fellow-attendance/', save_fellow_attendance, name='save_fellow_attendance'),
    path('fellow/attendance/history/<str:mobile_number>/', get_fellow_attendance_history, name='get_fellow_attendance_history'),
    

]
